name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php:
    name: Run PHP Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, sqlite, pdo_mysql
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: none

      - name: Install Composer deps
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Generate application key
        run: php artisan key:generate --ansi

      - name: Run migrations
        run: php artisan migrate --force --env=testing

      - name: Run PHPUnit
        run: php artisan test --no-interaction --env=testing

  js:
    name: Build & Lint JS
    runs-on: ubuntu-latest
    needs: php
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node deps
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Build assets
        run: npm run build 